### ISSUE TITLE
Email gets formatted unintentionally

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#21]
Input
```blade
someone@example.com
```

Output
```blade
someone
@example
.com
```

Expected input to remain unchanged.

**Comment by JohnathonKoster** [comment]
Bug fixed in `1.1.4`

**Comment by zepfietje** [comment]
Just tested this.

Works fine on initial run of Prettier.
But when you have this Blade file:

```blade
test@example.com
```

A new line gets added after formatting:
```blade
test@example.com

```

Then, when you run Prettier again:
```blade
hey
@zepfietje
.com
```

The initial example provided in this bug report might have been too simplified.
In my project I have something along the lines of:

```blade
<a>
    test@example.com
</a>
```

This still gets formatted to:

```blade
<a>
    test
    @example
    .com
</a>
```

**Comment by JohnathonKoster** [comment]
I've spotted the issue and made the "is this a directive" check a bit smarter in `1.1.5` (that's one thing the PHP version of this parser easier - it knows for certain what the directives already are 😅)

I've also added some test coverage to ensure there are not regressions on this item (even after formatting the output twice): https://github.com/Stillat/blade-parser-typescript/blob/main/src/test/formatter_templates.test.ts#L387-L395

**Comment by zepfietje** [comment]
Perfect, can confirm it works fine now!
